controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Pengguna;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends BaseController
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout',],
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }
    
    public function actionAlur()
    {
        return $this->render('alur');
    }
    
    public function actionSyarat()
    {
        return $this->render('syarat');
    }

    public function actionRegister()
    {
        $this->view->title = 'Daftar';
        $model = new Pengguna();

        if ($model->load(\Yii::$app->request->post())) {
            //$model->attributes = \Yii::$app->request->post('Pengguna');
            if ($model->validate()) {
                // form inputs are valid, do something here
                $model->generatePassword($model->password);
                if($model->save(false)){
                    \Yii::$app->getSession()->setFlash('success','Pendaftaran berhasil. Silahkan Masuk menggunakan username dan password anda');
                    return $this->redirect(['site/login']);
                }else{

                }
            }
        }

        return $this->render('register', [
            'model' => $model,
        ]);
    }

    public function actionLogin()
    {

        //var_dump( Yii::$app->user->isGuest);

        if (!Yii::$app->user->isGuest) {

            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/site/alur.php
<?php

/* @var $this yii\web\View */

$this->title = 'Elektronik Pelayanan Perizinan Terpadu';
?>

<div class="site-index">

    <div class="jumbotron">
        <img src="<?= \yii\helpers\Url::to('/img/alur.jpg') ?>"
    </div>


</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.old.php
<?php

/* @var $this yii\web\View */

$this->title = 'Elektronik Pelayanan Perizinan Terpadu';
?>
<div class="box box-default">
    <div class="box-header with-border">
<div class="site-index">

    <div class="jumbotron">
        <h3>SELAMAT DATANG DI PERIZINAN ONLINE PROVINSI GORONTALO </h3>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

        </div>
    </div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Elektronik Pelayanan Perizinan Terpadu';
?>

<div class="site-index">

    <div class="jumbotron">
        <h3>SELAMAT DATANG DI PERIZINAN ONLINE PROVINSI GORONTALO </h3>

        <p class="lead">Sistem Perizinan ini di peruntukan bagi pemohon yang ingin mengurus permohonan secara online.</p>

        <?php if(Yii::$app->user->isGuest){ ?>
        <p><a class="btn btn-lg btn-success" href="<?= \yii\helpers\Url::to(['site/register']) ?>">Daftar Sekarang</a></p>
        <?php }else { ?>
        <p><a class="btn btn-lg btn-success" href="<?= \yii\helpers\Url::to(['permohonan/izin']) ?>">Ajukan Sekarang</a></p>
        <?php } ?>
    </div>


</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/register.php
<?php
/**
 * Created by IntelliJ IDEA.
 * User: aisatriani
 * Date: 23/02/16
 * Time: 21:26
 */
use app\models\LevelPengguna;
use app\models\Pengguna;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;
use yii\helpers\ArrayHelper;


/* @var $form ActiveForm */
/* @var $model Pengguna */

#$this->title = 'Form Tambah Perizinan';
$this->params['breadcrumbs'] = [

    'Daftar',
];



?>


    <div class="box-header with-border">
        <?= $this->title ?>

    </div>

    <div class="box-body">

<!--            <form class="form-horizontal">-->
                <?php $form = ActiveForm::begin(['layout' => 'horizontal']); ?>
                <?php //echo $form->errorSummary($model); ?>
                <div class="box-body">


                        <?= $form->field($model, 'nik') ?>
                        <?= $form->field($model, 'nama') ?>
                        <?= $form->field($model, 'email') ?>
                        <?= $form->field($model, 'username') ?>
                        <?= $form->field($model, 'password')->passwordInput() ?>
                        <?= $form->field($model, 'password_repeat')->passwordInput() ?>


                    <div class="form-group">
                        <div class="col-md-12 col-md-offset-1">
                            <div class="box-header with-border col-sm-3">
                                Detil Alamat

                            </div>
                        </div>
                    </div>

                        <?= $form->field($model, 'id_provinsi')->dropDownList(
                            ArrayHelper::map(\app\models\Provinsi::find()->all(), 'id_prov','nama_prov'),
                            ['prompt'=>'Pilih Provinsi']
                        ) ?>
                        <?= $form->field($model, 'id_kabupaten')->dropDownList(
                            //ArrayHelper::map(\app\models\Kabupaten::find()->all(), 'id_kab','nama_kab'),
                            ['prompt'=>'Pilih Kabupaten/Kota']
                        ) ?>
                        <?= $form->field($model, 'id_kecamatan')->dropDownList(
                        //ArrayHelper::map(\app\models\Kabupaten::find()->all(), 'id_kab','nama_kab'),
                            ['prompt'=>'Pilih Kecamatan']
                        ) ?>
                        <?= $form->field($model, 'id_kelurahan')->dropDownList(
                        //ArrayHelper::map(\app\models\Kabupaten::find()->all(), 'id_kab','nama_kab'),
                            ['prompt'=>'Pilih Kelurahan']
                        ) ?>
                        <?= $form->field($model, 'alamat') ?>
                        <?= $form->field($model, 'telp') ?>




                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <div class="col-md-4 col-md-offset-4">
                        <button type="reset" class="btn btn-default btn80">Reset</button>
                        <?= Html::submitButton('Daftar', ['class' => 'btn btn-primary btn80']) ?>
                    </div>

                </div>
                <!-- /.box-footer -->
        <?php ActiveForm::end(); ?>

    </div>

views/site/syarat.php
<?php

/* @var $this yii\web\View */

$this->title = 'Syarat dan ketentuan permohonan perizinan';
?>

<div class="site-index">
<div class="container">



        <p><strong>1. IZIN USAHA BONGKAR MUAT DI PELABUHAN</strong></p>
        <p>A. PERSYARATAN</p>
        <p>Administrasi</p>
        <ol>
            <li>Memiliki Akta Pendirian Perusahaan (BHI)</li>
            <li>Memiliki NPWP Perusahaan</li>
            <li>Memiliki modal usaha</li>
            <li>Memiliki penanggung jawab</li>
            <li>Menenmpati tempat usaha, baik milik sendiri maupn sewa, berdasarkan surat keterangan domisili perusahaan dari instansi yang berwenang</li>
            <li>Memiliki tenaga ahli dan kualifikasi nautika atau ahli ketatalaksanaan pelayanan niaga</li>
        </ol>
        <p>Teknis (Disesuaikan dengan pelabuhan)</p>
        <p>B. WAKTU PENYELESAIAN PELAYANAN</p>
        <p>C. BIAYA PELAYANAN</p>
        <p>Tidak dikenakan biaya</p>
        <p>&nbsp;</p>
        <p><strong>2. IZIN USAHA JASA PENGURUSAN TRANSPORTASI (JPT)</strong></p>
        <p>A. PESYARATAN</p>
        <p>Adminisrasi</p>
        <ol>
            <li>Memiliki Akta Pendirian Perusahaan</li>
            <li>Memiliki Nomor Pokok Wajib Pajak Perusahaan</li>
            <li>Memiliki Modal Usaha</li>
            <li>Memiliki Penanggung Jawab</li>
            <li>Memiliki peralatan yang cukup sesuai dengan perkembangan teknologi</li>
            <li>Memiliki tenaga ahli yang sesuai</li>
            <li>Memiliki surat keterangan domisili perusahaan</li>
        </ol>
        <p>B. WAKTU PENYELESAIAN PELAYANAN</p>
        <p>3 (tiga) hari kerja sejak tanggal diterimanya berkas permohonan secara lengkap dan benar</p>
        <p>C. BIAYA PELAYANAN</p>
        <p>TIdak dikenakan biaya</p>
        <p>&nbsp;</p>
        <p><strong>3. IZIN TRAYEK AKDP</strong></p>
        <p>A. PERSAYARATAN</p>
        <p>Administrasi</p>
        <ol>
            <li>Fotocopy KTP Pemilik</li>
            <li>Fotocopy STNKB</li>
            <li>Fotocopy Buku Kir yang masih berlaku</li>
            <li>Fotocopy Jasa Raharja</li>
            <li>Rekomendasi Izin Trayek Asal Tujuan</li>
            <li>Kenderaan tersebut layak operasional</li>
        </ol>
        <p>B. WAKTU PENYELESAIAN PELAYANAN</p>
        <ul>
            <li>Untuk perpanjangan Kartu Pengawasan (KP)&nbsp;&plusmn;5 &ndash; 10 menit jika berkas permohonan sudah lengkap dan benar</li>
            <li>Untuk pengurusan Izin Trayek Baru selama 1 (satu) hari kerja sejak tanggal diterimanya berkas permohonan secara lengkap dan benar</li>
        </ul>
        <p>C. BIAYA PELAYANAN</p>
        <p>Tidak dikenakan biaya</p>
        <p>&nbsp;</p>

</div>

</div>